# Generated by Django 3.1.8 on 2021-07-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(max_length=5),
        ),
        migrations.DeleteModel(
            name='UserCustomDrink',
        ),
    ]
