# Generated by Django 3.1.8 on 2021-07-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_auto_20210729_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktails',
            name='description',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='cocktails.Ingredient'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='preparation',
            field=models.TextField(null=True),
        ),
    ]
