# Generated by Django 3.1.8 on 2021-07-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_auto_20210729_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
    ]
