# Generated by Django 3.1.8 on 2021-07-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_remove_ingredient_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='type',
        ),
    ]
