# Generated by Django 3.1.8 on 2021-07-30 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_auto_20210729_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cocktails',
            new_name='Cocktail',
        ),
    ]
