# Generated by Django 3.1.8 on 2021-07-31 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_auto_20210729_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
