# Generated by Django 3.1.8 on 2021-07-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0010_auto_20210730_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='ingredient_measures',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
