# Generated by Django 3.1.8 on 2021-07-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0011_cocktail_ingredient_measures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='ingredient_measures',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='garnish',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
