# Generated by Django 3.1.8 on 2021-08-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0014_auto_20210804_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='userName',
        ),
    ]
